server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testspring?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

      spring:
        cache:
          type: ehcache
          ehcache:
            config: classpath:/config/ehcache.xml

        spring:
          thymeleaf:
            prefix: classpath:/templates/
            cache: false


    spring:
        mvc:
            static-path-pattern: /static/**


#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
#    注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改


